// <auto-generated />
using Conf.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Conf.Migrations
{
    [DbContext(typeof(ConferenceContext))]
    [Migration("20180421171426_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Conf.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Conf.Models.ConferenceUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Cities");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Cities");

                    b.ToTable("ConferenceUsers");
                });

            modelBuilder.Entity("Conf.Models.ConferenceUser", b =>
                {
                    b.HasOne("Conf.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
